#!/bin/bash

##############################################
# 🤖 Build and Run Android App
# Builds React app and deploys to emulator
##############################################

set -e  # Exit on error

echo "=============================================="
echo "🤖 L3V3L Matrimony - Build & Run Android"
echo "=============================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Check if running from correct directory
if [ ! -f "../frontend/package.json" ]; then
    echo "❌ Error: Must run from deploy_gcp directory"
    exit 1
fi

cd ../frontend

# Production backend URL for Android APK
BACKEND_URL="https://matrimonial-backend-7cxoxmouuq-uc.a.run.app"

# Save current configs for restoration after build
echo -e "${BLUE}📝 Configuring for production build...${NC}"
if [ -f "public/config.js" ]; then
    cp public/config.js public/config.js.dev.backup
fi
if [ -f ".env.local" ]; then
    cp .env.local .env.local.dev.backup
fi

# Write production .env.android (used by React build)
cp .env.android .env.local
echo -e "${GREEN}✅ .env.local set to production (from .env.android)${NC}"

# Write production config.js (same as deploy_frontend_full.sh does)
cat > public/config.js << EOF
/**
 * Runtime Configuration (auto-generated by build_android.sh)
 */
window.RUNTIME_CONFIG = {
  ENVIRONMENT: 'production',
  SOCKET_URL: '${BACKEND_URL}',
  API_URL: '${BACKEND_URL}/api/users',
  WS_URL: 'wss://${BACKEND_URL#https://}',
  ENABLE_WEBSOCKETS: true,
  ENABLE_NOTIFICATIONS: true,
  DEBUG: false,
  LOG_LEVEL: 'INFO'
};
console.log('✅ Runtime config loaded for', window.RUNTIME_CONFIG.ENVIRONMENT, '| Log Level:', window.RUNTIME_CONFIG.LOG_LEVEL);
EOF
echo -e "${GREEN}✅ Production config.js written (Backend: ${BACKEND_URL})${NC}"
echo ""

# Check if Android project exists
if [ ! -d "android" ]; then
    echo -e "${RED}❌ Android project not found${NC}"
    echo ""
    echo "Please run setup first:"
    echo "  cd deploy_gcp"
    echo "  ./setup_android.sh"
    exit 1
fi

# Set up Android SDK paths
if [ -z "$ANDROID_HOME" ]; then
    export ANDROID_HOME=$HOME/Library/Android/sdk
fi
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Set JAVA_HOME to Android Studio's bundled JDK
if [ -z "$JAVA_HOME" ]; then
    export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
fi

# Check if emulator is available
echo -e "${BLUE}📋 Checking for Android emulators...${NC}"
EMULATOR_CMD="$ANDROID_HOME/emulator/emulator"
ADB_CMD="$ANDROID_HOME/platform-tools/adb"

EMULATOR_LIST=$($EMULATOR_CMD -list-avds 2>/dev/null || echo "")
if [ -z "$EMULATOR_LIST" ]; then
    echo -e "${RED}❌ No Android emulators found${NC}"
    echo "Please create an emulator in Android Studio first."
    exit 1
fi
echo -e "${GREEN}✅ Found emulators:${NC}"
echo "$EMULATOR_LIST" | sed 's/^/   /'
echo ""

# Check if emulator is already running
echo -e "${BLUE}📋 Checking running devices...${NC}"
RUNNING_DEVICES=$($ADB_CMD devices | grep -v "List of devices" | grep "device$" | wc -l | tr -d ' ')

if [ "$RUNNING_DEVICES" -eq "0" ]; then
    echo -e "${YELLOW}⚠️  No emulator running${NC}"
    echo "Starting emulator..."
    
    # Get first available emulator
    FIRST_EMULATOR=$(echo "$EMULATOR_LIST" | head -n 1)
    echo "Launching: $FIRST_EMULATOR"
    
    # Start emulator in background
    $EMULATOR_CMD -avd "$FIRST_EMULATOR" -no-snapshot-load > /dev/null 2>&1 &
    EMULATOR_PID=$!
    
    echo -e "${BLUE}⏳ Waiting for emulator to boot...${NC}"
    echo "   (This may take 30-60 seconds)"
    
    # Wait for device to be ready
    $ADB_CMD wait-for-device
    
    # Wait for boot to complete
    while [ "$($ADB_CMD shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != "1" ]; do
        sleep 2
        echo -n "."
    done
    echo ""
    echo -e "${GREEN}✅ Emulator booted${NC}"
else
    echo -e "${GREEN}✅ Emulator already running${NC}"
fi
echo ""

# Build React app
echo -e "${BLUE}📦 Step 1: Building React app...${NC}"
echo "   Running: npm run build"
npm run build
BUILD_SIZE=$(du -sh build 2>/dev/null | cut -f1)
echo -e "${GREEN}✅ React app built (Size: ${BUILD_SIZE})${NC}"
echo ""

# Copy to Android
echo -e "${BLUE}📲 Step 2: Copying web assets to Android...${NC}"
npx cap copy android
echo -e "${GREEN}✅ Web assets copied${NC}"
echo ""

# Sync native code
echo -e "${BLUE}🔄 Step 3: Syncing native dependencies...${NC}"
npx cap sync android
echo -e "${GREEN}✅ Native code synced${NC}"
echo ""

# Build and install APK
echo -e "${BLUE}🏗️  Step 4: Building and installing APK...${NC}"
cd android

# Clean previous build (optional, uncomment if needed)
# ./gradlew clean

# Build debug APK
./gradlew assembleDebug

if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
    echo -e "${RED}❌ Failed to build APK${NC}"
    exit 1
fi

APK_SIZE=$(du -h app/build/outputs/apk/debug/app-debug.apk | cut -f1)
echo -e "${GREEN}✅ APK built (Size: ${APK_SIZE})${NC}"
echo ""

# Install on emulator
echo -e "${BLUE}📲 Step 5: Installing on emulator...${NC}"
$ADB_CMD install -r app/build/outputs/apk/debug/app-debug.apk
echo -e "${GREEN}✅ App installed${NC}"
echo ""

# Launch app
echo -e "${BLUE}🚀 Step 6: Launching app...${NC}"
$ADB_CMD shell am start -n com.l3v3l.matrimony/.MainActivity
echo -e "${GREEN}✅ App launched${NC}"
echo ""

# Show logs
echo "=============================================="
echo -e "${GREEN}🎉 App Running on Emulator!${NC}"
echo "=============================================="
echo ""
echo "📱 App: L3V3L Matrimony"
echo "📦 APK: app/build/outputs/apk/debug/app-debug.apk"
echo "💾 Size: ${APK_SIZE}"
echo ""
echo "🔍 Debug Tools:"
echo "   • Chrome DevTools: chrome://inspect"
echo "   • View logs: $ADB_CMD logcat | grep L3V3L"
echo "   • Stop app: $ADB_CMD shell am force-stop com.l3v3l.matrimony"
echo "   • Uninstall: $ADB_CMD uninstall com.l3v3l.matrimony"
echo ""
echo "♻️  Rebuild & redeploy:"
echo "   ./build_android.sh"
echo ""

# Restore development configs
cd ..
echo -e "${BLUE}📝 Restoring development configs...${NC}"

# Restore config.js
if [ -f "public/config.js.dev.backup" ]; then
    mv public/config.js.dev.backup public/config.js
    echo -e "${GREEN}✅ Development config.js restored${NC}"
else
    cat > public/config.js << EOF
/**
 * Runtime Configuration (for local development)
 */
window.RUNTIME_CONFIG = {
  ENVIRONMENT: 'development',
  SOCKET_URL: 'http://localhost:8000',
  API_URL: 'http://localhost:8000/api/users',
  WS_URL: 'ws://localhost:8000',
  ENABLE_WEBSOCKETS: true,
  ENABLE_NOTIFICATIONS: true,
  DEBUG: true,
  LOG_LEVEL: 'DEBUG'
};
console.log('✅ Runtime config loaded for', window.RUNTIME_CONFIG.ENVIRONMENT, '| Log Level:', window.RUNTIME_CONFIG.LOG_LEVEL);
EOF
    echo -e "${GREEN}✅ Development config.js created${NC}"
fi

# Restore .env.local
if [ -f ".env.local.dev.backup" ]; then
    mv .env.local.dev.backup .env.local
    echo -e "${GREEN}✅ Development .env.local restored${NC}"
else
    cat > .env.local << EOF
# Local Development Environment
REACT_APP_BACKEND_URL=http://localhost:8000
REACT_APP_FRONTEND_URL=http://localhost:3000
EOF
    echo -e "${GREEN}✅ Development .env.local created${NC}"
fi
echo ""

# Optional: Show live logs
read -p "Show live logs? (y/n): " SHOW_LOGS
if [ "$SHOW_LOGS" = "y" ] || [ "$SHOW_LOGS" = "Y" ]; then
    echo ""
    echo "📋 Live Logs (Ctrl+C to stop):"
    echo "----------------------------------------------"
    $ADB_CMD logcat | grep -i "matrimony\|chromium\|capacitor"
fi
