steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/matrimonial-backend:latest'
      - '-f'
      - 'Dockerfile.prod'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/matrimonial-backend:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'matrimonial-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/matrimonial-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--cpu-boost'

images:
  - 'gcr.io/$PROJECT_ID/matrimonial-backend:latest'
