name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'fastapi_backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    name: Run Tests First
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          cd fastapi_backend
          pip install -r requirements.txt
          pip install pytest
      
      - name: Run tests
        env:
          MONGODB_URL: mongodb://localhost:27017
          TESTING: true
        run: |
          cd fastapi_backend
          pytest -v
  
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: matrimonial-staging

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Deploy to Cloud Run
        run: |
          cd fastapi_backend
          gcloud run deploy matrimonial-backend \
            --source . \
            --region us-central1 \
            --project matrimonial-staging \
            --allow-unauthenticated \
            --platform managed \
            --quiet

      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe matrimonial-backend \
            --region us-central1 \
            --project matrimonial-staging \
            --format="value(status.url)")
          echo "✅ Deployed to: $SERVICE_URL"
